### ISSUE TITLE
Old setuptools may be used when "setuptools" is required (more likely to affect older Pythons like 3.7)

### ISSUE THREAD

**Issue by henryiii** [FFY00/python-build#108]
Pybind11's build process (in current master) does perform a few tricks. But it works perfectly with `pip wheel` and `pep517.build`. *And* `python -m build`, **but only** if using Python 3.6 or 3.8. In Python 3.7, it fails with one of two errors:

Building with just the output sdist in the directory (either `python -m build` or `python -m build -w` after building the sdist):
There is an error (below) and the dist directory is gone after the command.

<details><summary>Click to expand</summary>

```
removing build/bdist.macosx-10.7-x86_64/wheel
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py", line 280, in <module>
    main()
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py", line 205, in build_wheel
    metadata_directory)
  File "/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-55xcdz6_/lib/python3.7/site-packages/setuptools/build_meta.py", line 176, in build_wheel
    shutil.copytree('dist', wheel_directory)
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'dist'
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/Caskroom/miniconda/base/envs/pybind11test/bin/python', '/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py', 'build_wheel', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpgicpuv66']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/build/__init__.py", line 215, in build
    raise BuildBackendException('Backend operation failed: {}'.format(e))
build.BuildBackendException: Backend operation failed: Command '['/usr/local/Caskroom/miniconda/base/envs/pybind11test/bin/python', '/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py', 'build_wheel', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpgicpuv66']' returned non-zero exit status 1.

ERROR Backend operation failed: Command '['/usr/local/Caskroom/miniconda/base/envs/pybind11test/bin/python', '/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py', 'build_wheel', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpgicpuv66']' returned non-zero exit status 1.
```

</details>

Making an SDist with another SDist present in the directory (pybind11 can make an alternate SDist):
There is an error (below). The directory remains intact.

<details><summary>Click to expand</summary>

```
Creating tar archive
removing 'pybind11-2.6.0.dev1' (and everything under it)
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py", line 280, in <module>
    main()
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-w0z4p4jx/lib/python3.7/site-packages/setuptools/build_meta.py", line 188, in build_sdist
    return _file_with_extension(sdist_directory, '.tar.gz')
  File "/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-w0z4p4jx/lib/python3.7/site-packages/setuptools/build_meta.py", line 94, in _file_with_extension
    file, = matching
ValueError: too many values to unpack (expected 1)
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/Caskroom/miniconda/base/envs/pybind11test/bin/python', '/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpbgghz54l']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/build/__init__.py", line 215, in build
    raise BuildBackendException('Backend operation failed: {}'.format(e))
build.BuildBackendException: Backend operation failed: Command '['/usr/local/Caskroom/miniconda/base/envs/pybind11test/bin/python', '/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpbgghz54l']' returned non-zero exit status 1.

ERROR Backend operation failed: Command '['/usr/local/Caskroom/miniconda/base/envs/pybind11test/bin/python', '/usr/local/Caskroom/miniconda/base/envs/pybind11test/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpbgghz54l']' returned non-zero exit status 1.
```

(To reproduce, just run sdist creation twice, once with `PYBIND11_GLOBAL_SDIST` set.)

</details>

Again, in both cases, this only happens with 3.7:

```bash
# macOS 10.15, Miniconda from brew
git clone https://github.com/pybind/pybind11
cd pybind11
conda create -n pybind11test python~=3.7
conda activate pybind11test
pip install build
python -m build -s
python -m build -w # BROKEN
# SDist directory gone

python -m build -s
PYBIND11_GLOBAL_SDIST=1 python -m build -s # Second line breaks, regardless of which one you do first
```

change the 3.7 to 3.8 _or_ 3.6, and both cases above work flawlessly.

It seems to only happen in conda - testing in CI works on linux and macOS when set to 3.7 and given the same dependencies. But it was reported and I was able to reproduce.

<details><summary>pip list</summary>

```
Package            Version
------------------ -------------------
build              0.0.4
certifi            2020.6.20
importlib-metadata 2.0.0
packaging          20.4
pep517             0.8.2
pip                20.2.2
pyparsing          2.4.7
setuptools         49.6.0.post20200925
six                1.15.0
toml               0.10.1
wheel              0.35.1
zipp               3.2.0
```

(zipp is not present in 3.8 or 3.6 env, but removing it doesn't affect anything)

</details>

**Comment by FFY00** [comment]
Hum, okay. This is a bit weird. I think the first error has already been solved in #80, but is weird it only doesn't work on conda.

Perhaps @pganssle could shed some more light into the setuptools error. That seems to me like a setuptools issue -- it is only expecting one matching sdist in the directory -- but we need to look into.

If you don't mind, could you test using python-build from `master`, this way we can isolate the current issues.

**Comment by henryiii** [comment]
No, latest master still shows the deleting "dist" bug. That fix couldn't have fixed it, as far as I can tell, since "dist" is being deleted by the "-w" part of the processes.

```bash
$ python -m build -s
... OK
$ ls dist
pybind11-2.6.0.dev1.tar.gz
$ python -m build -w
... ERROR
$ ls dist
ls: dist: No such file or directory
```

It really seems like a non-temporary directory (dist) is being used as if it was a temporary directory, which would explain why it's breaking when multiple files are already in it, and why it's being deleted when it thinks it needs to build a wheel.

**Comment by FFY00** [comment]
Ah, sorry! All this is seeming very setuptools specific.

@pganssle is it possible that setuptools is building a sdist in the process of building a wheel and using the `dist` directory without checking what/if it is there.

**Comment by pganssle** [comment]
I cannot reproduce this on Python 3.7, and the fact that it works for @henryiii in Python 3.6 and 3.8 makes me suspect that the issue is something to do with our poor / leaky isolation and an old installation of `setuptools` getting picked up somewhere.

The "cannot build an sdist if another one already exists" sounds a lot like https://github.com/pypa/setuptools/issues/1749, which would have been fixed in v41.1.0.

@henryiii Any chance you can modify the `setup.py` to print `setuptools.__version__` or something, so that we can be sure of what version of setuptools is getting picked up?

**Comment by henryiii** [comment]
Are you using conda? Possibly on a Mac? I couldn't reproduce on 3.7 on CI either, both on linux and macOS. I can try conda in a docker container...

`pep517.build` works fine, though, which is really odd, since the process looks pretty similar between `build` and `pep517.build`.

50.3.0 for pep517.build, 40.8.0 for build. Interesting! Is it not picking up setuptools from `pyproject.toml`?

**Comment by FFY00** [comment]
I think what is happening here is that ensurepip is fetching an older setuptools. Could you try updating the setuptools version in the requirements to be at least 41.1.0?

**Comment by henryiii** [comment]
Ahh, interesting. If I force setuptools>42 in pyproject.toml (which I usually do), then it's fine. `build` seems to be finding an old setuptools and installing it when no version is specified, while `pep517.build` is getting the latest one. I bet the setuptools cached file <42 is sitting around for Python 3.7 on the two machines, which is why it's grabbing that.

**Comment by henryiii** [comment]
That's valid behavior, though odd that it's different between the packages. Don't think that is build's fault.

**Comment by pganssle** [comment]
`pep517.build`'s build isolation is extremely rudimentary.

I think that the issue with the old `setuptools` will be fixed when we fix the issue where `ensurepip` installs `setuptools` (either by not using `ensurepip` or by uninstalling setuptools before the build runs). Not quite sure if #97 and #98 are implicated as well, but as we improve the isolation I think it will remove more and more of this kind of edge case.

**Comment by henryiii** [comment]
Feel free to close if you want, this is fixable by requiring setuptools>42. I do think requiring "setuptools" shouldn't install a really old version, though; many packages (like Pandas, which I just checked) just require "setuptools" without setting a minimum, and ideally in a fresh environment, I would assume that should get the latest one. So if you want to leave this open until that is fixed, also feel free to do that.
